os:
  - linux

language: python

python:
  - "3.6"
  - "3.7"

env:
  jobs:
    - TORCH_VERSION=1.4.0 TORCHVISION_VERSION=0.5.0 IDX=cpu
    - TORCH_VERSION=1.5.0 TORCHVISION_VERSION=0.6.0 IDX=cpu
    - TORCH_VERSION=1.6.0 TORCHVISION_VERSION=0.7.0 IDX=cpu
    - TORCH_VERSION=1.7.0 TORCHVISION_VERSION=0.8.1 IDX=cpu
    - TORCH_VERSION=1.8.0 TORCHVISION_VERSION=0.9.0 IDX=cpu

install:
  - pip install numpy
  - pip install snap-stanford
  - pip install networkx
  - pip install nose
  - pip install torch==${TORCH_VERSION}+${IDX} torchvision==${TORCHVISION_VERSION}+${IDX} -f https://download.pytorch.org/whl/torch_stable.html
  - |
    if [[ ${TORCH_VERSION} == "1.4.0" || ${TORCH_VERSION} == "1.5.0" ]]; then
      pip install torch-scatter==latest+${IDX} -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}.html
      pip install torch-sparse==latest+${IDX} -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}.html
      pip install torch-cluster==latest+${IDX} -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}.html && 
      pip install torch-spline-conv==latest+${IDX} -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}.html
    else
      pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html && 
      pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html && 
      pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html && 
      pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
    fi
  - pip install torch-geometric
  - python setup.py install

script:
  - python setup.py test
